[font]
normal      = { family = "JetBrainsMono", style = "Regular" }
bold        = { family = "JetBrainsMono", style = "Bold" }
italic      = { family = "JetBrainsMono", style = "Italic" }
bold_italic = { family = "JetBrainsMono", style = "Bold Italic" }
size        = 13

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[colors.cursor]
text   = "0x282828"
cursor = "0xebdbb2"

[colors.vi_mode_cursor]
text   = "0x282828"
cursor = "0xebdbb2"

[colors.selection]
text       = "0x282828"
background = "0xa89984"

[colors.search.matches]
foreground = "0x282828"
background = "0xbdae93"

[colors.search.focused_match]
foreground = "0x282828"
background = "0xfabd2f"

[colors.normal]
black   = "0x282828"
red     = "0xcc241d"
green   = "0x98971a"
yellow  = "0xd79921"
blue    = "0x458588"
magenta = "0xb16286"
cyan    = "0x689d6a"
white   = "0xa89984"

[colors.bright]
black   = "0x928374"
red     = "0xfb4934"
green   = "0xb8bb26"
yellow  = "0xfabd2f"
blue    = "0x83a598"
magenta = "0xd3869b"
cyan    = "0x8ec07c"
white   = "0xebdbb2"

[[colors.indexed_colors]]
index = 16
color = "0xd65d0e"

[[colors.indexed_colors]]
index = 17
color = "0xfe8019"
